name: Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create output-pacman branch if not exists
        run: |
          if ! git ls-remote --heads origin output-pacman | grep output-pacman; then
            git checkout --orphan output-pacman
            git rm -rf .
            git commit --allow-empty -m "Initial empty commit"
            git push origin output-pacman
            git checkout main
          fi

      - name: Generate Pacman SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Prepare output
        run: |
          mkdir -p dist/pacman
          mv pacman-contribution-graph.svg dist/pacman/

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-pacman
          build_dir: dist/pacman
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
